name: Swift

on: [push]

jobs:
  build:

    runs-on: macos-12

    steps:
      - run: brew install sqlite3
      - uses: actions/checkout@v3

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
        with:
          limit-access-to-actor: true
          limit-access-to-users: relrod

      - name: Build
        run: swift build
      - name: Run tests
        run: swift test
