name: Swift

on: [push]

jobs:
  build:

    runs-on: macos-12

    steps:
      - run: brew install sqlite3
      - uses: actions/checkout@v3
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test
